spring:
  application:
    name: terminal-service
  mongodb:
    uri: mongodb://terminal_service:terminal_service@localhost:27017/terminal_service

server:
  port: 9081

eureka:
  client:
    enabled: false

